include:
  - board: seeeduino_xiao_ble
    shield: totem_left
  - board: seeeduino_xiao_ble
    shield: totem_right
    # Probably not needed
  - board: seeeduino_xiao_ble
    shield: settings_reset
    artifact-name: seed_reset
